Add Geometric image in website
ohyajk/portfolio1 pull request #2
Opened 2022-10-27 16:11 UTC by ohyajk

I added HTML, CSS and geometric image.

2022-10-27 22:56 UTC, tufoinnkuo10 requested changes
Hi @ohyajk 
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally

Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-10-27 22:56 UTC, tufoinnkuo10 commented on index.html
> +        <button class="about-btn">
- [ ]  kindly add a link placeholder to the get my CV button. This will assist in future to take you to your cv on click

2022-10-27 22:56 UTC, tufoinnkuo10 commented on index.html
> +                <p class="folio-heading">Project name goes here</p>
- [ ] please The project title (e.g., project name goes here) use a header tag hx(2,3,4)

2022-10-27 22:56 UTC, tufoinnkuo10 commented on index.html
> +                        See this Project
- [ ] See this project should be a link/ button as it will enable u get to the project . please fix that for all

2022-10-28 05:02 UTC, Tadesse-Alemayehu approved these changes
### Hi @ohyajk 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![ZLnP](https://user-images.githubusercontent.com/69077061/198506629-409ba387-70c8-4186-bf2a-07533d2a0017.gif)

## Highlights
 - [ ] Good job overall following the template design 💯
 - [ ]  Correct GitHub Flow 👍🏾
 - [ ]  Good commit history 🥇
 - [ ]  Good PR title/description 💯
 - [ ]  All linters passed 🥇
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 07:56 UTC, merged